config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get 'user/:id', :to => 'users#show', as: :user
  get 'static_pages/home'

  get 'front_page/intro'
  
  resources :microtablas
  resources :memberships
  resources :posts
  resources :invitacions
  
    namespace :api, defaults: {format: 'json'} do
        namespace :v1 do
            resources :users
            resources :sessions
            resources :microtablas
            resources :posts
            resources :invitacions
        end
    end

   root 'front_page#intro'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  # validates :auth_token, uniqueness: true

  has_many :microtablas, dependent: :destroy 
  has_many :memberships, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :invitacions

  def generate_authentication_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end

  before_create :generate_authentication_token!

  def skip_confirmation!
  self.confirmed_at = Time.now
end

end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < ApplicationController
  after_action :set_access_control_headers
   respond_to :json  

  def show
    parametros = params[:user][:link]
    @user = User.find_by(:id => parametros)
    #@users = User.second
    respond_to do |format|
  format.json { render json: @user.to_json}
  format.xml
end
  end

    def create
    @user = User.new(user_params)
    @user.generate_authentication_token!
    if @user.save
      respond_to do |format|
  format.json { render json: @user.to_json}
  format.xml 
end
    else
      render json: { errors: @user.errors }, status: 422
    end
  end
end

 private
 def set_access_control_headers
   headers['Access-Control-Allow-Origin'] = "*"
   headers['Access-Control-Request-Method'] = %w{GET POST OPTIONS}.join(",")
 end

  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :link)
    end

app/controllers/users/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
  
end

app/controllers/users/sessions_controller.rb
class SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/unlocks_controller.rb
class UnlocksController < Devise::UnlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :js

  def show
  	@user = User.find(params[:id])
  	@microtablas = current_user.microtablas.all
  	@invitacion = Invitacion.all
  	@marco = Microtabla.all

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<!-- <div class="view third-effect">  
  <img src="/assets/person.jpg" />  
  <div class="mask"></div>
  <div class="content">  
    <a href="#" class="info" title="Full Image">Full Image</a>  
  </div>  
</div>  -->





<div class="galleria">
<div  id="content">
 <% @microtablas.each do |micro| %>  
  <div class="boxportfolio3 cat1">
    <div class="boxcontainer">
      <% if micro.posts.first.present? %>
         <%= image_tag micro.posts.first.image_url(:cartel),class: "filter-image" %>
         <% else %>
         <img class="dibujo" src="/assets/placeholder.png" alt="">
         <% end %>
      
      <div class="roll">
        <div class="wrapcaption">
          <a><%= link_to "", invitacion_path(micro), remote: true, class: "icon-link captionicons" %></a>
          <a  href="<%= microtabla_path(micro) %>" title="La Chaux De Fonds"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a class="cotenido"><%= micro.content %></a></h1>
      <p class="parrafo">
         <% if micro.descripcion.present? %>
         <%= micro.descripcion %>
  
          <% end %> 
      </p>
    </div>
  </div>
  <% end %>
   <% @invitacion.each do |macro| %>
  <% if macro.user_id != current_user.id && macro.contacto == current_user.email  %>
    <% @part = Microtabla.find_by(:id => macro.microtabla_id ) %>
    <div class="boxportfolio3 cat1">
    <div class="boxcontainer">
      <% if @part.posts.first.present? %>
         <%= image_tag @part.posts.first.image_url(:cartel) %>
         <% else %>
         <img class="dibujo" src="/assets/placeholder.png" alt="">
         <% end %>
      
      <div class="roll">
        <div class="wrapcaption">
          <a><%= link_to "", invitacion_path(@part), remote: true, class: "icon-link captionicons" %></a>
          <a  href="<%= microtabla_path(@part) %>" title="La Chaux De Fonds"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a class="cotenido"><%= @part.content %></a></h1>
      <p class="parrafo">
         <% if @part.descripcion.present? %>
         <%= @part.descripcion %>
  
          <% end %> 
      </p>
    </div>
  </div>
      

   <% end %>
  
  <% end %> 
</div>
</div>


<div class="container">
  <div class="new-product"></div>
  <div id="product-modal" class="modal fade">
<div class="modal-dialog">
<div id="inner-product-modal" class="modal-content"></div>
</div>
</div>

<div class="container">
  <div class="new-product"></div>
  <div id="members-modal" class="modal fade">
<div class="modal-dialog">
<div id="inner-members-modal" class="modal-content"></div>
</div>
</div>


  <!-- 
  <% @invitacion.each do |macro| %>
  <% if macro.user_id != current_user.id && macro.contacto == current_user.email  %>
    <% @part = Microtabla.find_by(:id => macro.microtabla_id ) %>
    <div class="boxportfolio3 cat1">
    <div class="boxcontainer">
      <% if @part.posts.first.present? %>
         <%= image_tag @part.posts.first.image_url(:cartel) %>
         <% else %>
         <img class="dibujo" src="/assets/placeholder.png" alt="">
         <% end %>
      
      <div class="roll">
        <div class="wrapcaption">
          <a href="<%= invitacion_path(macro) %>"><i class="icon-link captionicons"></i></a>
          <a  href="<%= microtabla_path(macro) %>" title="La Chaux De Fonds"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a class="cotenido"><%= @part.content %></a></h1>
      <p class="parrafo">
         <% if @part.descripcion.present? %>
         <%= @part.descripcion %>
  
          <% end %> 
      </p>
    </div>
  </div>
      

   <% end %>
  
  <% end %> 
  
 -->
<!-- <div class="galleria">
<div id="content">
    <div class="boxportfolio3 cat1">
    <div class="boxcontainer">
      <img class="dibujo" src="/assets/person.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/2.jpg" title="Taj Mahal"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">Taj Mahal</a></h1>
      <p>
         one of the eight wonders
      </p>
    </div>
  </div>

  
    <div class="boxportfolio3 cat1">
    <div class="boxcontainer">
      <img class="dibujo" src="/assets/person.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/2.jpg" title="Taj Mahal"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">Taj Mahal</a></h1>
      <p>
         one of the eight wonders
      </p>
    </div>
  </div>

 
    <div class="boxportfolio3 cat1">
    <div class="boxcontainer">
      <img class="dibujo" src="/assets/person.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/2.jpg" title="Taj Mahal"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">Taj Mahal</a></h1>
      <p>
         one of the eight wonders
      </p>
    </div>
  </div>
</div>
</div>
   -->


<!-- <header class="jumbotron hero-spacer">
    <p class="nombre"><h1><%= @user.name %></h1></p>
</header>
<div class="foto">
<% if @user.avatar_url.nil? %>
<a>
          <img src="/assets/person.jpg" alt="" class="responsive img-circle">
        </a>
<% else %>
<%= image_tag @user.avatar_url(:display), class: "responsive img-circle" %><br />
<% end %>
 
</div>
<% if current_user == @user %>
<div  class="camara" >
<a href= <%= edit_user_registration_path %> <span  class="glyphicon glyphicon-camera">
</a>
</div>
<% else %>
<% end %>
<nav class="pronav navbar navbar-default" role="navigation">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand navbar-brand-centered">Enviar perfil</div>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#"><%= @user.microtablas.count %> tableros</a></li>
        <li><a href="#">0 pines</a></li>
        <li><a href="#">0 "me gusta"</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">0 seguidores</a></li>
        <li><a href="#">0 siguiendo</a></li>
      </ul>
    </div>
  </div>
</nav>
 -->
<!-- <div id="masonry-container">
<% if current_user == @user %>

  <div class="col-md-3">
    <a ><%= link_to "Crear tabla", new_microtabla_path, class: "thumbnail" %>
      
    </a>
  </div>
<% else %>
<% end %>
<% @user.microtablas.each do |micro| %> 
  <div class="col-md-3">
    <a class="ventana thumbnail" href="<%= microtabla_path(micro) %>">
      <div class="panel-heading">
                    <h3 class="panel-title"><%=  micro.user_id %><%=current_user.id %><%= micro.content %><%= micro.id %></h3> 
                    <% @invitacion.each do |macro| %>

                    <% if current_user.email == macro.contacto && micro.id == macro.microtabla_id || current_user == @user  %> 

  <div class="col-md-3">
    <a class="ventana thumbnail" href="<%= microtabla_path(micro) %>">
      <div class="panel-heading">
                    <h3 class="panel-title"><%= micro.content %></h3>
 


</div>
      
    </a>
  </div>
  <% break if current_user.email == macro.contacto && micro.id == macro.microtabla_id  || current_user == @user %> 
  <% end %>


<% end %>

 
      
 <% end %> -->
  