config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  get 'user/:id', :to => 'users#show', as: :user
  get 'static_pages/home'

  get 'front_page/intro'
  
  resources :microtablas
  resources :memberships
  resources :posts
  resources :invitacions
  
    namespace :api, defaults: {format: 'json'} do
        namespace :v1 do
            resources :users
            resources :sessions
            resources :microtablas
            resources :posts
            resources :invitacions
        end
    end

   root 'front_page#intro'

end

app/models/microtabla.rb
class Microtabla < ActiveRecord::Base
	belongs_to :user
	has_many :memberships, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :invitacions
	accepts_nested_attributes_for :posts

	default_scope -> { order('created_at DESC') }
	validates :content, presence: true, length: { maximum: 30 }

	validates :user_id, presence: true
end

app/controllers/api/v1/microtablas_controller.rb
class API::V1::MicrotablasController < ApplicationController
after_action :set_access_control_headers
   respond_to :json 

     def index
     @microtablas = Microtabla.first
    #@microtablas = Microtabla.all
    respond_to do |format|
  format.json { render json: @microtablas.to_json}
  format.xml
end
end

   def show
    parametros = params[:microtabla][:user_id]
    if params[:microtabla][:tipo] == "primero"
      @micro = Microtabla.where(user_id: parametros)
      @microtablas = @micro.first
      respond_to do |format|
        format.json { render json: @microtablas.to_json}
        format.xml
      end
    else
      @microtablas = Microtabla.where(:user_id => parametros)
      @user = User.find_by(:id => parametros)
      invitacions = Invitacion.where(:contacto => @user.email)
      #@microtablas = Microtabla.all
      @album = Microtabla.where(:user_id => parametros)
      part =[]
      @microtablas.each do |macro|
        macro.avatar = @user.avatar 
        #@avatar = User.find_by(:id => cara.user_id)
        part << macro  
      end
      invitacions.each do |macro|
        cara = Microtabla.find_by(:id => macro.microtabla_id)
        @avatar = User.find_by(:id => cara.user_id)
        cara.avatar = @avatar.avatar
        part << cara 
      end
      respond_to do |format|
        format.json { render json: part.to_json}
        format.xml
      end
    end 
  end
  

    


    def create
    	@microtabla = Microtabla.new(microtabla_params)
    	if @microtabla.save
    		respond_to do |format|
    			format.json { render json: @microtabla.to_json}
    			format.xml 
    		end
    	else
    		render json: { errors: @microtabla.errors }, status: 422
    	end
    end

  def destroy
    
    @microtabla = Microtabla.find(params[:id])
    @microtabla.destroy
    respond_to do |format|
          format.json { render json: @microtabla.to_json}
          format.xml 
        end
  end

end

 private
 def set_access_control_headers
   headers['Access-Control-Allow-Origin'] = "*"
   headers['Access-Control-Request-Method'] = %w{GET POST OPTIONS}.join(",")
 end

 def microtabla_params
    params.require(:microtabla).permit(:content, :user_id, :tipo, :avatar, :nombreuser, :link)
  end

app/controllers/microtablas_controller.rb
class MicrotablasController < ApplicationController
  respond_to :html, :js
  
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

	def new
    @microtabla = current_user.microtablas.build
	end

  def show
    @microtabla = Microtabla.find(params[:id])
    @membership = @microtabla.memberships.all
    @post =  @microtabla.posts.all
    @member = Membership.find_by(:microtabla_id => @microtabla )
    @part = Invitacion.find_by(:microtabla_id => @microtabla )

    
  end

	  def create
    @microtabla = current_user.microtablas.build(microtabla_params)
    if @microtabla.save
      redirect_to user_path(current_user) 
    else
     redirect_to user_path(current_user)
    end
  end
  def edit
    @microtabla = current_user.microtablas.find(params[:id])
  end

  def update
    @microtablas = Microtabla.all
    @microtabla = Microtabla.find(params[:id])
    
    @microtabla.update_attributes(microtabla_params)
    redirect_to @microtabla
  end

  def destroy
    @microtabla.destroy
    redirect_to user_path(current_user)
  end

  private

  def microtabla_params
    params.require(:microtabla).permit(:content, :descripcion)
  end

  def membership_params
    params.require(:membership).permit(:microtabla_id, :user_id)
  end

  def correct_user
      @microtabla = current_user.microtablas.find_by(id: params[:id])
      redirect_to redirect_to user_path(current_user) if @microtabla.nil?
  end

   def invitacion_params
    params.require(:invitacion).permit(:contacto, :user_id, :microtabla_id)
  end
end

app/helpers/microtablas_helper.rb
module MicrotablasHelper
end

app/views/microtablas/_create.js.erb
<%= render "save" %>

app/views/microtablas/_edit.html.erb
<%= render 'form' %>

app/views/microtablas/_form.html.erb
<%= form_for @microtabla, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
  <div class="modal-body">
   

    <div class="control-group">
      <%= f.label :nombre, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :content, class: "form-control", :maxlength => 30%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :pequeña_descripcion, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :descripcion,  class: "form-control", :maxlength => 30 %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "Crear album", class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>
  
<!-- 
<%= form_for (@microtabla) do |f| %>
<div class="container">
	<div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
          <form class="form-horizontal" action="" method="post">
          <fieldset>
            <legend class="text-center"></legend>
	<p>
	  <%= f.label :nombre %><br/>
	  <%= f.text_field :content %>
	</p>
	<p>
	  <%= f.label :pequeña_descripcion %><br/>
	  <%= f.text_field :descripcion %>
	</p>
	<p>
	  <%= f.submit %>
	  <%= link_to "cancelar", user_path(current_user) %>
	</p>
		
</div>
</fieldset>
          </form>
        </div>
      </div>
	</div>
</div>
<% end %> -->

app/views/microtablas/_new.html.erb
<div class=" modal-header">
<h3>Nuevo Album</h3>
</div>
<%= render 'form' %>

app/views/microtablas/_save.js.erb
$(".product-index").html("<%= escape_javascript(render 'index') %>")
$("#product-modal").modal("hide")

app/views/microtablas/create.js.erb
$(".product-index").html("<%= escape_javascript(render 'show') %>")
$("#product-modal").modal("hide")

app/views/microtablas/edit.js.erb
$("#inner-product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/microtablas/new.js.erb
$("#inner-product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/microtablas/show.html.erb
<div class="titulo-album">
 
    <h1><%= @microtabla.content %></h1>
  
</div>

<nav class="pronav navbar navbar-default" role="navigation">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div ><%= link_to "Enviar invitacion", new_invitacion_path(microtabla_id: @microtabla.id), remote: true, class: "navbar-brand navbar-brand-centered"  %></div>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a>fotos: <%= @microtabla.posts.count %> </a></li>
        <li><a class="miembros-link"><%= link_to "miembros", invitacion_path(@microtabla), remote: true %></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Subir foto", new_post_path(microtabla_id: @microtabla.id), remote: true    %></li>
      <% if current_user == @microtabla.user %>
        <li><%= link_to "Borrar album", @microtabla, method: :delete, data: {confirm: 'Estas seguro?'} %></li>
        <li><%= link_to "editar album", edit_microtabla_path(@microtabla), remote: true %>
      </li>
      
<% end %>
      </ul>
    </div>
  </div>
</nav>


<!-- <li><a ><%= link_to "nuevo album", new_microtabla_path, remote: true, class: "create btn btn-lg" %> </a></li> -->

<!-- <div class="margen-foto"> -->
<div id="content">
  <% @post.each do |t| %>  
  <div class="boxportfolio4 cat2 ">
    <div class="boxcontainer"><a id="<%=t.id %>">
      <%= image_tag t.image_url(:thumbnail)%>
      </a>
      <div class="roll">
        <div class="wrapcaption">
          
          <a data-gal="prettyPhoto[gallery1]" href=<%= t.image_url(:thumb)%>><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html"><%=t.description %></a></h1>
      
         <% if t.user.avatar_url.nil? %>
          <img src="/assets/person.jpg" alt="" class="responsive-small responsive img-circle">
        
        
<% else %>
        <%= image_tag t.user.avatar_url(:tag), class: "responsive-small img-circle" %>

        <% end %>
        <% if current_user %>
        <% if current_user.id == t.user_id %>
        <%= form_for(current_user.posts.find_by(id: t.id),html: { method: :delete }) do |f| %>
        <%= link_to edit_post_path(t.id, microtabla_id: @microtabla.id ), remote: true, class: "boton-editar btn btn-default" do %>
    <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= button_tag(type: 'submit', class: "boton-delete btn btn-default pull-right") do %>
  <span class="glyphicon glyphicon-remove pull-right"></span>  
<% end %>
        <% end %>
        
        <% end %>
<% end %>
      
    </div>
  </div>
  <% end %>
</div>
</div>


<div class="container">
  <div class="new-product"></div>
  <div id="product-modal2" class="modal fade">
<div class="modal-dialog">
<div id="inner-product-modal2" class="modal-content"></div>
</div>
</div>

<div class="container">
  <div class="new-product"></div>
  <div id="members-modal" class="modal fade">
<div class="modal-dialog">
<div id="inner-members-modal" class="modal-content"></div>
</div>
</div>

<div class="container">
  <div class="new-product"></div>
  <div id="product-modal" class="modal fade">
<div class="modal-dialog">
<div id="inner-product-modal" class="modal-content"></div>
</div>
</div>

<div class="container">
  <div class="new-product"></div>
  <div id="invitacion-modal" class="modal fade">
<div class="modal-dialog">
<div id="inner-invitacion-modal" class="modal-content"></div>
</div>
</div>
<!--   
  <div class="row-fluid">
    <div class="span12 text-center">
      <div id="filter">
        <ul>
          <li><a href="" data-filter="*" class="selected"><i class="icon icon-reorder"></i> All Items</a></li>
          <li><a href="" data-filter=".cat1"><i class="icon icon-th-large"></i> Landscape</a></li>
          <li><a href="" data-filter=".cat2"><i class="icon icon-th-list"></i> Overview</a></li>
          <li><a href="" data-filter=".cat3"><i class="icon icon-th"></i> Green Nature</a></li>
        </ul>
      </div>
    </div>
  </div>
 

<div id="content">
    
  <div class="boxportfolio4 cat2 ">
    <div class="boxcontainer">
      <img src="/assets/1.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/1.jpg" title="La Chaux De Fonds"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">La Chaux De Fonds</a></h1>
      <p>
         Swiss city in Jura mountains
      </p>
    </div>
  </div>
  
  <div class="boxportfolio4 cat2">
    <div class="boxcontainer">
      <img src="/assets/2.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/2.jpg" title="Taj Mahal"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">Taj Mahal</a></h1>
      <p>
         one of the eight wonders
      </p>
    </div>
  </div>
  
  <div class="boxportfolio4 cat2">
    <div class="boxcontainer">
      <img src="/assets/3.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/3.jpg" title="Title Here"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">Versailles, France</a></h1>
      <p>
         Cotelle Gallery
      </p>
    </div>
  </div>
  
  <div class="boxportfolio4 cat2">
    <div class="boxcontainer">
      <img src="/assets/4.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/4.jpg" title="Title Here"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">St Petersburg, Russia</a></h1>
      <p>
         water fountain
      </p>
    </div>
  </div>
  
  <div class="boxportfolio4 cat2">
    <div class="boxcontainer">
      <img src="/assets/5.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/5.jpg" title="Title Here"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">Grunge Architecture</a></h1>
      <p>
        ancient style Europe
      </p>
    </div>
  </div>


  
  <div class="boxportfolio4 cat2">
    <div class="boxcontainer">
      <img src="/assets/6.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/6.jpg" title="Title Here"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">France Building</a></h1>
      <p>
         old towers architecture
      </p>
    </div>
  </div>

    <div class="boxportfolio4 cat2">
    <div class="boxcontainer">
      <img src="/assets/4.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/4.jpg" title="Title Here"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">St Petersburg, Russia</a></h1>
      <p>
         water fountain
      </p>
    </div>
  </div>

    <div class="boxportfolio4 cat2 ">
    <div class="boxcontainer">
      <img src="/assets/1.jpg" alt="">
      <div class="roll">
        <div class="wrapcaption">
          <a href="singleproject.html"><i class="icon-link captionicons"></i></a>
          <a data-gal="prettyPhoto[gallery1]" href="img/temp/masonry/1.jpg" title="La Chaux De Fonds"><i class="icon-zoom-in captionicons"></i></a>
        </div>
      </div>
      <h1><a href="singleproject.html">La Chaux De Fonds</a></h1>
      <p>
         Swiss city in Jura mountains
      </p>
    </div>
  </div>
</div> -->

<!-- <div class="container">
  <div class="new-product"></div>
  <div id="product-modal" class="modal fade">
<div class="modal-dialog">
<div id="inner-product-modal" class="modal-content"></div>
</div>
</div>
<h1 class="titular"><%= @microtabla.content %></h1>


<nav class="pronav navbar navbar-default" role="navigation">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user == @microtabla.user %>
      <div ><%= link_to "Enviar tablero", new_invitacion_path(microtabla_id: @microtabla.id), class: "navbar-brand navbar-brand-centered"  %></div>
    </div>
       <% end %>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a>miembros: <%= @membership.count %> </a></li>
        <li><a href="#">0 "me gusta"</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><a ><%= form_for(current_user.memberships.build) do |f| %>
  <div><%= f.hidden_field :microtabla_id, :value => @microtabla.id%></div>
  <div><%= f.hidden_field :user_id, :value => current_user.id%></div>  
  <%= f.submit "Apuntarse", class: "btn btn-large btn-primary" %>
<% end %></a></li>
<% else %>
<% end %>
<% if current_user == @microtabla.user %>
<li><%= link_to "Subir foto", new_post_path(microtabla_id: @microtabla.id)  %></li>
<% else %>
<li><a>
  <% if current_user %>
<% @membership.each do |t| %>
<% if current_user.id == t.user_id  %>
        <%= form_for(current_user.memberships.find_by(microtabla_id: @microtabla),html: { method: :delete }) do |f| %>
  <%= f.submit "borrarse", class: "btn btn-large" %>
 
  <% end %>
  <li><%= link_to "Subir foto", new_post_path(microtabla_id: @microtabla.id)  %></li>
<% else %>
<% end %>
   
<% end %>
<% end %>
<% end %>
 </a></li>

        <% if current_user == @microtabla.user %>
        <li><%= link_to "Borrar tabla", @microtabla, method: :delete, data: {confirm: 'Estas seguro?'} %></li>
        <% else %>
<% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="col-md-2">
<ul class="vertical nav  nav-stacked">
  
<div id="  masonry-container">
  <% @post.each do |t| %>
  <div class="col-md-2">
    <div class="cartelera panel panel-default">
      <div class="panel-body">
        <%= image_tag t.image_url(:thumbnail) %><br />
      </div>
      <div class="panel-footer">
        <%= t.description %><br />
        <% if current_user %>
        <% if current_user.id == t.user_id %>
        <%= form_for(current_user.posts.find_by(microtabla_id: @microtabla),html: { method: :delete }) do |f| %>
        <%= f.submit "borrar", class: "btn btn-large" %>
        <%= link_to "Editar", edit_post_path(t.id, microtabla_id: @microtabla.id ) %>
        <% end %>
        <% else %>
        <% end %>
<% end %>
     <% if t.user.avatar_url.nil? %>
          <img src="/assets/person.jpg" alt="" class="carita responsive img-circle">
        
<% else %>
        <%= image_tag t.user.avatar_url(:tag), class: "responsive img-circle" %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

</div>
 -->